django/django/00_django_intro/firstpjt/articles/urls.py
from django.urls import path
# 명시적 상대경로 표현
from . import views


app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>/', views.hello, name='hello'),
    # path('hello/<name>/', views.hello, name='hello'),
]

django/django/00_django_intro/firstpjt/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django/django/00_django_intro/firstpjt/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

django/django/00_django_intro/firstpjt/articles/models.py
from django.db import models

# Create your models here.

django/django/00_django_intro/firstpjt/pages/models.py
from django.db import models

# Create your models here.

django/django/00_django_intro/firstpjt/articles/views.py
import random
from django.shortcuts import render

# Create your views here.
def index(request): # 첫번째 인자는 반드시 request
    return render(request, 'articles/index.html') # render 함수의 첫번째 인자는 반드시 request


def greeting(request):
    foods = ['apple', 'banana', 'coconut',]
    info = {
        'name': 'Harry'
    }
    context = {
        'info': info,
        'foods': foods,
    }
    return render(request, 'articles/greeting.html', context)


def dinner(request):
    foods = ['족발', '피자', '햄버거', '초밥',]
    pick = random.choice(foods)
    context = {
        'pick': pick,
        'foods': foods,
    }
    return render(request, 'articles/dinner.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    message = request.GET.get('message')
    # print(message)
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def hello(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/hello.html', context)

django/django/00_django_intro/firstpjt/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

django/django/00_django_intro/firstpjt/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>CATCH</h1>
  <h2>여기서 {{ message }}를 받았어 !!!</h2>

  <a href="{% url 'articles:throw' %}">다시 던지러!!</a>
{% endblock %}

django/django/00_django_intro/firstpjt/articles/templates/articles/dinner.html
{% extends 'base.html' %}

{% block content %}
  <h1>오늘 저녁은 {{ pick }}!!</h1>
  <p>{{ pick }}은 {{ pick|length }}</p>
  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {# 이것은 주석입니다 #}

  {% comment %}
    <p>1</p>
    <p>2</p>
    <p>3</p>
  {% endcomment %}
  
  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock %}

django/django/00_django_intro/firstpjt/articles/templates/articles/greeting.html
{% extends 'base.html' %}

{% block content %}
  <h1>안녕하세요. 저는 {{ info.name }} 입니다.</h1>
  <p>제가 좋아하는 음식은 {{ foods }}입니다.</p>
  <p>{{ foods.0 }}을 가장 좋아합니다.</p>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock %}

django/django/00_django_intro/firstpjt/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello</h1>
  <h2>만나서 반가워요 {{ name }}님!!!</h2>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock %}

django/django/00_django_intro/firstpjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>만나서 반가워요!!!</h1>
  <a href="{% url 'articles:greeting' %}">greeting</a>
  <a href="{% url 'articles:dinner' %}">dinner</a>
  <a href="{% url 'articles:throw' %}">throw</a>

  <a href="{% url 'pages:index' %}">두번째 앱의 인덱스</a>
{% endblock %}

django/django/00_django_intro/firstpjt/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>THROW</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw: </label>
    <input type="text" name="message" id="message">
    <input type="submit">
  </form>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock %}

django/django/00_django_intro/firstpjt/firstpjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>